/*
 * This file is generated by jOOQ.
 */
package my.starter.jooq.keys


import my.starter.jooq.tables.User
import my.starter.jooq.tables.records.UsersRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val UNIQUE_EMAIL: UniqueKey<UsersRecord> = Internal.createUniqueKey(User.USERS, DSL.name("unique_email"), arrayOf(User.USERS.EMAIL), true)
val USERS_PKEY: UniqueKey<UsersRecord> = Internal.createUniqueKey(User.USERS, DSL.name("users_pkey"), arrayOf(User.USERS.ID), true)
