/*
 * This file is generated by jOOQ.
 */
package my.starter.jooq.enums


import my.starter.jooq.DefaultSchema

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class UserGender(@get:JvmName("literal") public val literal: String) : EnumType {
    MALE("MALE"),
    FEMALE("FEMALE");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getName(): String = "user_genders"
    override fun getLiteral(): String = literal
}
